/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VlechtenTongerenRouteImport } from './routes/vlechten-tongeren'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as PrijzenRouteImport } from './routes/prijzen'
import { Route as SalonCoiffureTongresRouteImport } from './routes/salon-coiffure-tongres'
import { Route as CoiffeuseTongresRouteImport } from './routes/coiffeuse-tongres'
import { Route as BraidsLimburgRouteImport } from './routes/braids-limburg'
import { Route as NagelsTongerenRouteImport } from './routes/nagels-tongeren'
import { Route as MicroshadingTongerenRouteImport } from './routes/microshading-tongeren'
import { Route as KapsterTongerenRouteImport } from './routes/kapster-tongeren'
import { Route as KapsalonTongerenRouteImport } from './routes/kapsalon-tongeren'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as ExtensionsTongerenRouteImport } from './routes/extensions-tongeren'
import { Route as BoxBraidsTongerenRouteImport } from './routes/box-braids-tongeren'
import { Route as BeautySalonTongerenRouteImport } from './routes/beauty-salon-tongeren'
import { Route as AlgemeneVoorwaardenRouteImport } from './routes/algemene-voorwaarden'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AnnulerTokenRouteImport } from './routes/annuler.$token'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const VlechtenTongerenRoute = VlechtenTongerenRouteImport.update({
  id: '/vlechten-tongeren',
  path: '/vlechten-tongeren',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const PrijzenRoute = PrijzenRouteImport.update({
  id: '/prijzen',
  path: '/prijzen',
  getParentRoute: () => rootRouteImport,
} as any)
const NagelsTongerenRoute = NagelsTongerenRouteImport.update({
  id: '/nagels-tongeren',
  path: '/nagels-tongeren',
  getParentRoute: () => rootRouteImport,
} as any)
const MicroshadingTongerenRoute = MicroshadingTongerenRouteImport.update({
  id: '/microshading-tongeren',
  path: '/microshading-tongeren',
  getParentRoute: () => rootRouteImport,
} as any)
const KapsterTongerenRoute = KapsterTongerenRouteImport.update({
  id: '/kapster-tongeren',
  path: '/kapster-tongeren',
  getParentRoute: () => rootRouteImport,
} as any)
const KapsalonTongerenRoute = KapsalonTongerenRouteImport.update({
  id: '/kapsalon-tongeren',
  path: '/kapsalon-tongeren',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsTongerenRoute = ExtensionsTongerenRouteImport.update({
  id: '/extensions-tongeren',
  path: '/extensions-tongeren',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxBraidsTongerenRoute = BoxBraidsTongerenRouteImport.update({
  id: '/box-braids-tongeren',
  path: '/box-braids-tongeren',
  getParentRoute: () => rootRouteImport,
} as any)
const BeautySalonTongerenRoute = BeautySalonTongerenRouteImport.update({
  id: '/beauty-salon-tongeren',
  path: '/beauty-salon-tongeren',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgemeneVoorwaardenRoute = AlgemeneVoorwaardenRouteImport.update({
  id: '/algemene-voorwaarden',
  path: '/algemene-voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnulerTokenRoute = AnnulerTokenRouteImport.update({
  id: '/annuler/$token',
  path: '/annuler/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/beauty-salon-tongeren': typeof BeautySalonTongerenRoute
  '/box-braids-tongeren': typeof BoxBraidsTongerenRoute
  '/extensions-tongeren': typeof ExtensionsTongerenRoute
  '/galerie': typeof GalerieRoute
  '/kapsalon-tongeren': typeof KapsalonTongerenRoute
  '/kapster-tongeren': typeof KapsterTongerenRoute
  '/microshading-tongeren': typeof MicroshadingTongerenRoute
  '/nagels-tongeren': typeof NagelsTongerenRoute
  '/prijzen': typeof PrijzenRoute
  '/reservations': typeof ReservationsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vlechten-tongeren': typeof VlechtenTongerenRoute
  '/annuler/$token': typeof AnnulerTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/beauty-salon-tongeren': typeof BeautySalonTongerenRoute
  '/box-braids-tongeren': typeof BoxBraidsTongerenRoute
  '/extensions-tongeren': typeof ExtensionsTongerenRoute
  '/galerie': typeof GalerieRoute
  '/kapsalon-tongeren': typeof KapsalonTongerenRoute
  '/kapster-tongeren': typeof KapsterTongerenRoute
  '/microshading-tongeren': typeof MicroshadingTongerenRoute
  '/nagels-tongeren': typeof NagelsTongerenRoute
  '/prijzen': typeof PrijzenRoute
  '/reservations': typeof ReservationsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vlechten-tongeren': typeof VlechtenTongerenRoute
  '/annuler/$token': typeof AnnulerTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/beauty-salon-tongeren': typeof BeautySalonTongerenRoute
  '/box-braids-tongeren': typeof BoxBraidsTongerenRoute
  '/extensions-tongeren': typeof ExtensionsTongerenRoute
  '/galerie': typeof GalerieRoute
  '/kapsalon-tongeren': typeof KapsalonTongerenRoute
  '/kapster-tongeren': typeof KapsterTongerenRoute
  '/microshading-tongeren': typeof MicroshadingTongerenRoute
  '/nagels-tongeren': typeof NagelsTongerenRoute
  '/prijzen': typeof PrijzenRoute
  '/reservations': typeof ReservationsRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vlechten-tongeren': typeof VlechtenTongerenRoute
  '/annuler/$token': typeof AnnulerTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/algemene-voorwaarden'
    | '/beauty-salon-tongeren'
    | '/box-braids-tongeren'
    | '/extensions-tongeren'
    | '/galerie'
    | '/kapsalon-tongeren'
    | '/kapster-tongeren'
    | '/microshading-tongeren'
    | '/nagels-tongeren'
    | '/prijzen'
    | '/reservations'
    | '/services'
    | '/sitemap.xml'
    | '/vlechten-tongeren'
    | '/annuler/$token'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/algemene-voorwaarden'
    | '/beauty-salon-tongeren'
    | '/box-braids-tongeren'
    | '/extensions-tongeren'
    | '/galerie'
    | '/kapsalon-tongeren'
    | '/kapster-tongeren'
    | '/microshading-tongeren'
    | '/nagels-tongeren'
    | '/prijzen'
    | '/reservations'
    | '/services'
    | '/sitemap.xml'
    | '/vlechten-tongeren'
    | '/annuler/$token'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/algemene-voorwaarden'
    | '/beauty-salon-tongeren'
    | '/box-braids-tongeren'
    | '/extensions-tongeren'
    | '/galerie'
    | '/kapsalon-tongeren'
    | '/kapster-tongeren'
    | '/microshading-tongeren'
    | '/nagels-tongeren'
    | '/prijzen'
    | '/reservations'
    | '/services'
    | '/sitemap.xml'
    | '/vlechten-tongeren'
    | '/annuler/$token'
    | '/email/unsubscribe'
    | '/lovable/email/suppression'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlgemeneVoorwaardenRoute: typeof AlgemeneVoorwaardenRoute
  BeautySalonTongerenRoute: typeof BeautySalonTongerenRoute
  BoxBraidsTongerenRoute: typeof BoxBraidsTongerenRoute
  ExtensionsTongerenRoute: typeof ExtensionsTongerenRoute
  GalerieRoute: typeof GalerieRoute
  KapsalonTongerenRoute: typeof KapsalonTongerenRoute
  KapsterTongerenRoute: typeof KapsterTongerenRoute
  MicroshadingTongerenRoute: typeof MicroshadingTongerenRoute
  NagelsTongerenRoute: typeof NagelsTongerenRoute
  PrijzenRoute: typeof PrijzenRoute
  ReservationsRoute: typeof ReservationsRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VlechtenTongerenRoute: typeof VlechtenTongerenRoute
  AnnulerTokenRoute: typeof AnnulerTokenRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vlechten-tongeren': {
      id: '/vlechten-tongeren'
      path: '/vlechten-tongeren'
      fullPath: '/vlechten-tongeren'
      preLoaderRoute: typeof VlechtenTongerenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prijzen': {
      id: '/prijzen'
      path: '/prijzen'
      fullPath: '/prijzen'
      preLoaderRoute: typeof PrijzenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nagels-tongeren': {
      id: '/nagels-tongeren'
      path: '/nagels-tongeren'
      fullPath: '/nagels-tongeren'
      preLoaderRoute: typeof NagelsTongerenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/microshading-tongeren': {
      id: '/microshading-tongeren'
      path: '/microshading-tongeren'
      fullPath: '/microshading-tongeren'
      preLoaderRoute: typeof MicroshadingTongerenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapster-tongeren': {
      id: '/kapster-tongeren'
      path: '/kapster-tongeren'
      fullPath: '/kapster-tongeren'
      preLoaderRoute: typeof KapsterTongerenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kapsalon-tongeren': {
      id: '/kapsalon-tongeren'
      path: '/kapsalon-tongeren'
      fullPath: '/kapsalon-tongeren'
      preLoaderRoute: typeof KapsalonTongerenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions-tongeren': {
      id: '/extensions-tongeren'
      path: '/extensions-tongeren'
      fullPath: '/extensions-tongeren'
      preLoaderRoute: typeof ExtensionsTongerenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box-braids-tongeren': {
      id: '/box-braids-tongeren'
      path: '/box-braids-tongeren'
      fullPath: '/box-braids-tongeren'
      preLoaderRoute: typeof BoxBraidsTongerenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beauty-salon-tongeren': {
      id: '/beauty-salon-tongeren'
      path: '/beauty-salon-tongeren'
      fullPath: '/beauty-salon-tongeren'
      preLoaderRoute: typeof BeautySalonTongerenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algemene-voorwaarden': {
      id: '/algemene-voorwaarden'
      path: '/algemene-voorwaarden'
      fullPath: '/algemene-voorwaarden'
      preLoaderRoute: typeof AlgemeneVoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annuler/$token': {
      id: '/annuler/$token'
      path: '/annuler/$token'
      fullPath: '/annuler/$token'
      preLoaderRoute: typeof AnnulerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlgemeneVoorwaardenRoute: AlgemeneVoorwaardenRoute,
  BeautySalonTongerenRoute: BeautySalonTongerenRoute,
  BoxBraidsTongerenRoute: BoxBraidsTongerenRoute,
  ExtensionsTongerenRoute: ExtensionsTongerenRoute,
  GalerieRoute: GalerieRoute,
  KapsalonTongerenRoute: KapsalonTongerenRoute,
  KapsterTongerenRoute: KapsterTongerenRoute,
  MicroshadingTongerenRoute: MicroshadingTongerenRoute,
  NagelsTongerenRoute: NagelsTongerenRoute,
  PrijzenRoute: PrijzenRoute,
  SalonCoiffureTongresRoute: SalonCoiffureTongresRoute,
  CoiffeuseTongresRoute: CoiffeuseTongresRoute,
  BraidsLimburgRoute: BraidsLimburgRoute,
  ReservationsRoute: ReservationsRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VlechtenTongerenRoute: VlechtenTongerenRoute,
  AnnulerTokenRoute: AnnulerTokenRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
